Styling cleanup
TripleParity/docks-ui pull request #144
Opened 2018-07-20 10:29 UTC by FJMentz

Call me mr Styles. Updated the whole theme and extracted most css files to a general global file.

Also some other small fixes

----
Fixes #105 
Fixes #102 
Closes #106

2018-07-20 10:34 UTC, annamarieHelberg approved these changes
Looks good

2018-07-20 10:35 UTC, ghost approved these changes

2018-07-23 09:07 UTC, egeldenhuys approved these changes
Fixes #105 
Fixes #102 
Closes #106

2018-07-23 09:12 UTC, egeldenhuys commented on src/styles.css
>   */@import url("https://fonts.googleapis.com/css?family=Roboto:400,500,700");:root{--blue:#325D88;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#d9534f;--orange:#F47C3C;--yellow:#ffc107;--gr
Why is the bootstrap table theme included in `styles.css` and `styles-additional.css` ?

2018-07-23 09:13 UTC, annamarieHelberg commented
@FJMentz This really looks amazing. But, I do think we should look at having an option where a user can decide between styles (for example, dark theme and this light (official Compiax) theme).

2018-07-23 15:04 UTC, egeldenhuys requested changes
Will merge once the duplicate bootstrap table style is removed from style.css

2018-07-23 16:10 UTC, egeldenhuys approved these changes

2018-07-23 16:13 UTC, merged