Webhooks
TripleParity/docks-ui pull request #164
Opened 2018-09-20 20:29 UTC by CDuPlooy

Just a dummy page to add webhooks. Will work with the slack-poc-2 branch of the !api.

![](https://i.imgur.com/7kxRGBd.png)

I have not added anything to the navbar, so this page is available at /webhooks

2018-09-20 20:36 UTC, annamarieHelberg approved these changes
It looks really nice! But, I think @FJMentz  and @Paulo-W  can you maybe please look into making it prettier?

2018-09-20 21:08 UTC, FJMentz commented on src/app/pages/webhooks/webhooks-create/webhook-create.component.html
> +        <input type="submit">
As a start to avoid 'incomplete' errors, can you just add a disable condition to the submit to only be enabled when a name and a url is entered?

2018-09-20 21:08 UTC, FJMentz approved these changes
Great work! Just the minor comment I made that I'd like changed.

2018-09-21 01:36 UTC, egeldenhuys requested changes
Webhooks are working, well done!

To Do:
- [ ] If you are happy with the `slack-poc-2` branch, open a PR and get that merged first.
- [ ] Add navbar link

2018-09-21 08:33 UTC, CDuPlooy commented
PR is pending and navbar has been updated :+1:

2018-09-21 09:14 UTC, egeldenhuys approved these changes

2018-09-21 09:24 UTC, merged