Dynamic graphs
TripleParity/docks-ui pull request #185
Opened 2018-10-08 08:58 UTC by CDuPlooy

On mobile.

2018-10-08 09:32 UTC, egeldenhuys requested changes
The Offline/Online nodes chart is fine :+1: , however the chart on the left is comparing values that cannot be compared. The number of nodes compared to the number of networks does not provide any insights except "I have 1 node and 35 networks". Can we remove this chart or replace it with boxes showing the number of Nodes/networks/etc ?

The colour scheme is also better :+1:

2018-10-08 09:32 UTC, egeldenhuys commented on src/app/pages/services/service-detail-view/service-detail-view.component.ts
> +    )[0];
Did `prettier` change this formatting?

2018-10-08 09:44 UTC, CDuPlooy commented
I have absolutely no idea. X)

As per the chart; I'll make those changes when I have time :)

2018-10-08 09:46 UTC, annamarieHelberg commented
I think taking a look at swarmpit and portainer's graphs would help. But thank you for implementing it :+1:

2018-10-09 04:11 UTC, egeldenhuys requested changes
I realise logic tends to leave us at such late times, but can you please give 8a232da2233425481d84eed7c5096ac69571a462 a relevant comment?

2018-10-09 13:01 UTC, CDuPlooy commented
> I think taking a look at swarmpit and portainer's graphs would help. But thank you for implementing it

I [this](https://github.com/swarmstack/swarmstack) something like this would be nice.

I've removed the redundant graph and added cards.

![](https://i.imgur.com/6ohOxhk.png)

2018-10-11 21:44 UTC, egeldenhuys commented on src/app/pages/home/home.component.ts
> +    this.page_start = interval(30000).subscribe(() => {
This should help

2018-10-12 08:30 UTC, egeldenhuys approved these changes
Looks good

2018-10-12 08:31 UTC, ghost approved these changes
I like the new layout looks good !

2018-10-12 08:43 UTC, merged