Networks2
TripleParity/docks-ui pull request #89
Opened 2018-05-10 21:48 UTC by CDuPlooy

Make sure you visit /containers before trying any of the other components.

It will force an auth attempt with the api and acquire a token while we wait for the login component. Yes this is hacky; Yes you need this.

2018-05-10 21:51 UTC, FJMentz approved these changes

2018-05-10 22:36 UTC, FJMentz requested changes
uhmmm

2018-05-10 23:12 UTC, FJMentz approved these changes
Couldn't demo it, but I see no errors in the code

2018-05-11 07:34 UTC, annamarieHelberg approved these changes
I will add the card view now

2018-05-11 08:37 UTC, ghost approved these changes

2018-05-12 08:42 UTC, closed without merging